wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706889324.676763
    t:
      1:
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
